#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: first_to_know_development


test:
  <<: *default
  database: first_to_know_test


production:
  url: <%= ENV['PRODUCTION_DATABASE'] %>
